### ISSUE TITLE
Feedback de la evaluación intermedia del sprint 2

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/dorcar-s2-evaluacion-intermedia-Albametnet#1]
El html está demasiado trabajado si tenemos en cuenta que el JS no funciona. En estos casos mejor solucionamos la funcionalidad y luego ya lo ponemos bonito. El planteamiento tiene buena pinta pero no funciona y hay que solucionar varios puntos para echarlo a andar. Si te parece solucionamos los que falla y luego lo intentamos ajustar a un guión que te propondré:

### Errores a subsanar

- [ ] Hay que mostrar por consola el número elegido, no el resultado de la función ya que entonces tendremos por consola un número que no es el que almacenamos en la variable con la que vamos a trabajar
- [ ] Intentamos añadir un listener al botón sin almacenar previamente la referencia al elemento del DOM
- [ ] Cuando recogemos un dato del DOM, ya sea con innerHTMl o con .value siempre recogemos cadenas, y habrá que pasarlo a número
- [ ] Y ya que estamos, en la función de comparar tendremos que recoger el número que ha introducido el usuario, no la referencia al elemento del DOM ;)
- [ ] Ya que tenemos una comparacion con solo dos opciones, vamos  a seguir una estructura de `if () {} else if () {} else {}`
- [ ] Cuando asignamos cadenas (o números) no necesitamos los paréntesis: `var paco = "me llamo paco";`

Una vez hecho esto ya funcionaría nuestro ejercicío y sería el momento de reordenarlo un poco para que siga este guión (y terminar el contador ):

```
// Guardar la referencia a todos los elementos del DOM que vamos a usar en variables

// Generar el número aleatorio
// Y guardarlo en una variable

// Inicializar a 0 una variable de contador

// Crear una función que se ejecute cuando haga click en el botón de prueba
//  Esta función tiene que hacer:
//  1 - incrementar el contador
//  2 - y pintar el contador en mi html

//  3 - recoger el valor del campo
//  4 - Compararlo con mi número aleatorio
//    - Si son iguales -> pintar el mensaje de "Ganadora"
//    - Si es menor -> pintar el mensaje de "te has quedado corta"
//    - Si es mayor -> pintar el mensaje de "te has pasado"

// Asignar un listener al botón de prueba para que ejecute una función al hacer click
```
![Enough for today](https://media.giphy.com/media/Mp4hQy51LjY6A/giphy.gif)

**Comment by Albametnet** [comment]
ya me pongo con ello

**Comment by Albametnet** [comment]
lo he reescrito me parece incluso mas sencillo, pero hay problema.

**Comment by oneeyedman** [comment]
Claro que hay un problema: no has seguido el guión ni lo que te he sugerido. Y entonces hay varias funciones cuando en el guión solo habla de una. Y entonces hay un par de eventos enlazados al mismo elemento cuando eso no lo hemos hecho ni de lejos en el curso, ni se pide. Bueno, y no has reescrito el código, has vuelto a poner tu mismo código.
El guión está puesto para que vayáis siguiendo y viendo un camino, para ir poco a poco. Y una vez terminado ir ampliando.
